version: "3.9"

services:
  postgres_db:
    image: postgres:14
    restart: always
    volumes:
      - app-volume:/var/lib/postgresql/data/
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_DB=malscrapy-db
      - POSTGRES_USER=malscrapy-user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_db_password
    secrets:
      - postgres_db_password
    networks:
      - app-network
    ports:
      - "5432:5432"
  pg_admin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=malscrapyuser@example.com
      - PGADMIN_DEFAULT_PASSWORD_FILE=/run/secrets/pgadmin_password
      - PGADMIN_LISTEN_PORT=5431
    secrets:
      - pgadmin_password
    networks:
      - app-network
    ports:
      - "5431:5431"
  app:
    build: .
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    restart: always
    environment:
      - POSTGRES_DB=malscrapy-db
      - POSTGRES_USER=malscrapy-user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_db_password
    secrets:
      - postgres_db_password
    networks:
      - app-network
    depends_on:
      - postgres_db

secrets:
   postgres_db_password:
     file: ./postgres_db_password.txt
   pgadmin_password:
     file: ./pgadmin_password.txt

networks:
  app-network:
volumes:
  app-volume:
