name: MALScrapy application

on:
  push:
  pull_request:
    branches:
      - master
      - develop
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10"]
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Install dev dependencies
      run: pip install -r requirements-dev.txt
